# Generated by Django 3.2.7 on 2023-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_seed_sow_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='stratification',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
